project:
  type: website
  output-dir: docs

website:
  title: "ruthe808.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd
      - href: posts.qmd
        text: my posts

format:
  html:
    theme:
      - mystyles.scss
    mainfont: Lato
    css: styles.css
    toc: true

editor: visual

