project:
  type: website
  output-dir: docs

website:
  #title: Ruth Enriquez
  favicon: img/logo.png
  navbar:
      title: false
      logo: img/logo.png
      right:
      - href: index.qmd
        text: home
      - about.qmd
      - resume.qmd
      - href: posts.qmd
        text: my posts
  page-footer: 
      left:
      - "copywrite 2022, Ruth Eniquez"
format:
  html:
    theme:
      - mystyles.scss
    mainfont: Lato
    css: mystyles.scss
    toc: true

editor: visual

