project:
  type: website
  output-dir: docs

website:
  title: Ruth Enriquez
  favicon: img/susu_logo.png
  navbar:
      logo: img/susu_logo.png
      right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: EnriquezRuth_Resume.pdf
        text: Resume
      - href: posts.qmd
        text: Portfolio
  page-footer: 
      left:
      - "copywrite 2023, Ruth Eniquez"
format:
  html:
    theme:
      - mystyles.scss
    mainfont: Open Sans
    css: mystyles.scss
    toc: true

editor: visual