---
title: "About"
---

::: panel-tabset
## Full Bio

A little bit more about me... before attending the University of California, Santa Barbara (UCSB), I worked for Bank of Hawai'i, the largest local bank in the state. My career started with the bank when I was brought on as a student assistant. I was lucky to have managers that believed in my personal and professional development throughout my career, check out my short testimony on the [Bank of Hawaii IT Career page](https://www.boh.com/careers/information-technology). My managers nominated me for the bank's internship program, which taught me all about the inner workings of a bank, and later their management training program, which enhanced my interpersonal skills to work with vendors, contracts, customers, and fellow coworkers.

My manager continued to invest in my professional development and asked me consider pursuing a master's in business administration (MBA). I did consider getting a MBA till I saw an Instagram post about the MEDS program at UCSB. The program had the technical aspect that I loved about working in IT Finance, and it had the feel-good aspect of working on environmental/sustainability issues. So I opted to go back to school, but not for an MBA.

My passion for sustainability comes from being born and raised in Hawai'i. It was easy to fall in love with the environment when growing up Saturday mornings were spent at the beach with my dad and brothers and Sundays were spent hiking with friends. But part of growing up in Hawai'i is also seeing how limited our natural resources are and how that affects us.

In high school I did my senior project on food waste, where I wrote a research paper and had the opportunity to volunteer with [Aloha Harvest](https://alohaharvest.org/past-present-future/). I saw how many people suffered from food insecurity and how an organization turned a problem, like food waste, into a solution to helped to communities get feed.

Ideally, I would love my next career to be one where I can combine my IT finance experience with my passion in sustainability and newly gained data science skills. I hope to work in green technology, corporate sustainability, food waste and/or environmental, social, and corporate governance (ESG), but am open to other opportunities.

## Hobbies

-   Trying new restaurants with family and friends

-   Checking out local coffee shops and farmer's markets

-   Spending time at the beach

-   Traveling

"It seems that the more places I see and experience, the bigger I realize the world to be. The more I become aware of, the more I realize how relatively little I know of it, how many places I have still to go, how much more there is to learn." - Anthony Bourdain

A map of my travels so far :)

```{r, message= FALSE, warning= FALSE, echo= FALSE}
#load needed libraries
library(tidyverse)
library(here)
library(sf)
library(leaflet)
library(readxl)

#read in cities
places <- read_excel(here("data", "travel.xlsx"))

#add geometries to cities
places <- places %>% 
  st_as_sf(coords = c("lon",
                      "lat"),
            crs = 4326)

places %>% 
  leaflet() %>% 
  addProviderTiles(providers$Esri.WorldPhysical) %>% 
  addProviderTiles(providers$Stamen.TonerLabels) %>% 
  addMarkers(label = places$place)


```
:::
